### ISSUE TITLE
Candle windows 11

### ISSUE THREAD

**Issue by denhoy81** [Denvi/Candle#545]
Does Candle work on windows 11?

**Comment by mar0x** [comment]
Yes, it does.

**Comment by lrafuse1005** [comment]
i am having a terrible time making this work   i think i have tried everything but i am new to this   it starts, mills for a minute then stops   works longer everytime but never in the same spot

HELP!

**Comment by mar0x** [comment]
Hello,
To advise anything useful it would be good to know the details about your CNC (model, firmware, etc).

For now, I guess you are running Windows 11. One of the possible reason of the behavior you have described is unreliable CNC control board power or USB connection.

**Comment by lrafuse1005** [comment]
Thank you for replying!  I have a vevor 3018 prover
Sent from my iPhone

On Oct 16, 2023, at 3:39 AM, Max ***@***.***> wrote:

﻿

Hello,
To advise anything useful it would be good to know the details about your CNC (model, firmware, etc).

For now, I guess you are running Windows 11. One of the possible reason of the behavior you have described is unreliable CNC control board power or USB connection.

**Comment by lrafuse1005** [comment]
I read some more into some possible issues and decreased the windows running system to run windows eight for this particular product. It states it can run at 11, 10… But I am having trouble with issues that it is stopping. I will try this morning and see how it runs on windows eight and, let you know how I do. Thank you so much for your quick reply. I honestly didn’t know if anyone would reply since this thread is so outdated.
Sent from my iPhone

On Oct 17, 2023, at 6:53 AM, Lisa Rafuse ***@***.***> wrote:

﻿ Thank you for replying!  I have a vevor 3018 prover
Sent from my iPhone

On Oct 16, 2023, at 3:39 AM, Max ***@***.***> wrote:

﻿

Hello,
To advise anything useful it would be good to know the details about your CNC (model, firmware, etc).

For now, I guess you are running Windows 11. One of the possible reason of the behavior you have described is unreliable CNC control board power or USB connection.
